### ISSUE TITLE
Exception when initializing flows

### ISSUE THREAD

**Issue by mzilinec** [botshot/botshot#35]
```
Traceback (most recent call last):
  File "/home/web/showmax-bot/env/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/web/showmax-bot/env/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/web/showmax-bot/env/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/web/showmax-bot/env/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/web/showmax-bot/env/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/web/showmax-bot/env/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/web/showmax-bot/env/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/web/showmax-bot/bot/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/web/showmax-bot/env/lib/python3.5/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/web/showmax-bot/env/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/web/showmax-bot/env/lib/python3.5/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/home/web/showmax-bot/botshot/apps.py", line 10, in ready
    init_flows()
  File "/home/web/showmax-bot/botshot/core/flow.py", line 43, in init_flows
    print('Initialized {} flows: {}'.format(len(flows), sorted(list(flows.keys()))))
TypeError: unorderable types: bool() < str()
```

**Comment by mzilinec** [comment]
YAML issue, `yes` is implicitly converted to `true`. Why not.

**Comment by mzilinec** [comment]
TODO: add a warning to docs
