### ISSUE TITLE
Getting started instructions don't work

### ISSUE THREAD

**Issue by karthicraghupathi** [botshot/botshot#65]
I'm following the instructions [here](https://github.com/botshot/botshot#getting-started) but I end up with the following error when I run the `init` command:

```
$ bots init my_bot
Creating Botshot project in my_bot ...
Copying project files...
Installing botshot files from /Users/karthicr/.local/share/virtualenvs/botshot_project-XTuAZIk_/lib/python3.6/site-packages/botshot/bootstrap
Initializing database ...
Traceback (most recent call last):
  File "/Users/karthicr/.local/share/virtualenvs/botshot_project-XTuAZIk_/bin/bots", line 8, in <module>
    sys.exit(main())
  File "/Users/karthicr/.local/share/virtualenvs/botshot_project-XTuAZIk_/lib/python3.6/site-packages/botshot/bots.py", line 198, in main
    args.func(args)
  File "/Users/karthicr/.local/share/virtualenvs/botshot_project-XTuAZIk_/lib/python3.6/site-packages/botshot/bots.py", line 103, in init_project
    raise e
  File "/Users/karthicr/.local/share/virtualenvs/botshot_project-XTuAZIk_/lib/python3.6/site-packages/botshot/bots.py", line 98, in init_project
    execute_from_command_line(['_', 'migrate'])
  File "/Users/karthicr/.local/share/virtualenvs/botshot_project-XTuAZIk_/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/karthicr/.local/share/virtualenvs/botshot_project-XTuAZIk_/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/Users/karthicr/.local/share/virtualenvs/botshot_project-XTuAZIk_/lib/python3.6/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/Users/karthicr/.local/share/virtualenvs/botshot_project-XTuAZIk_/lib/python3.6/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/karthicr/.local/share/virtualenvs/botshot_project-XTuAZIk_/lib/python3.6/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/karthicr/.asdf/installs/python/3.6.12/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/folders/dy/1vzm3lbx1673twz_pmd8vcnmr40220/T/tmp9tmz70fr/bot/settings.py", line 132, in <module>
NameError: name 'os' is not defined
```

Here is some additional information to assist with troubleshooting:

```
$ python --version
Python 3.6.12

$ brew services list
redis             started karthicr /usr/local/opt/redis/homebrew.mxcl.redis.plist

$ pipenv graph
botshot==0.1.4
  - celery [required: >=4.1.1, installed: 5.1.0]
    - billiard [required: >=3.6.4.0,<4.0, installed: 3.6.4.0]
    - click [required: >=7.0,<8.0, installed: 7.1.2]
    - click-didyoumean [required: >=0.0.3, installed: 0.0.3]
      - click [required: Any, installed: 7.1.2]
    - click-plugins [required: >=1.1.1, installed: 1.1.1]
      - click [required: >=4.0, installed: 7.1.2]
    - click-repl [required: >=0.1.6, installed: 0.1.6]
      - click [required: Any, installed: 7.1.2]
      - prompt-toolkit [required: Any, installed: 3.0.18]
        - wcwidth [required: Any, installed: 0.2.5]
      - six [required: Any, installed: 1.16.0]
    - kombu [required: >=5.1.0,<6.0, installed: 5.1.0]
      - amqp [required: >=5.0.6,<6.0.0, installed: 5.0.6]
        - vine [required: ==5.0.0, installed: 5.0.0]
      - cached-property [required: Any, installed: 1.5.2]
      - importlib-metadata [required: >=0.18, installed: 4.0.1]
        - typing-extensions [required: >=3.6.4, installed: 3.10.0.0]
        - zipp [required: >=0.5, installed: 3.4.1]
      - vine [required: Any, installed: 5.0.0]
    - pytz [required: >dev, installed: 2021.1]
    - setuptools [required: Any, installed: 56.0.0]
    - vine [required: >=5.0.0,<6.0, installed: 5.0.0]
  - django [required: >=2.1.5, installed: 3.2.3]
    - asgiref [required: >=3.3.2,<4, installed: 3.3.4]
      - typing-extensions [required: Any, installed: 3.10.0.0]
    - pytz [required: Any, installed: 2021.1]
    - sqlparse [required: >=0.2.2, installed: 0.4.1]
  - djangorestframework [required: Any, installed: 3.12.4]
    - django [required: >=2.2, installed: 3.2.3]
      - asgiref [required: >=3.3.2,<4, installed: 3.3.4]
        - typing-extensions [required: Any, installed: 3.10.0.0]
      - pytz [required: Any, installed: 2021.1]
      - sqlparse [required: >=0.2.2, installed: 0.4.1]
  - elasticsearch [required: Any, installed: 7.13.0]
    - certifi [required: Any, installed: 2020.12.5]
    - urllib3 [required: >=1.21.1,<2, installed: 1.26.4]
  - emoji [required: Any, installed: 1.2.0]
  - jsonfield [required: Any, installed: 3.1.0]
    - Django [required: >=2.2, installed: 3.2.3]
      - asgiref [required: >=3.3.2,<4, installed: 3.3.4]
        - typing-extensions [required: Any, installed: 3.10.0.0]
      - pytz [required: Any, installed: 2021.1]
      - sqlparse [required: >=0.2.2, installed: 0.4.1]
  - mock [required: Any, installed: 4.0.3]
  - networkx [required: Any, installed: 2.5.1]
    - decorator [required: >=4.3,<5, installed: 4.4.2]
  - Pillow [required: Any, installed: 8.2.0]
  - pytest [required: Any, installed: 6.2.4]
    - attrs [required: >=19.2.0, installed: 21.2.0]
    - importlib-metadata [required: >=0.12, installed: 4.0.1]
      - typing-extensions [required: >=3.6.4, installed: 3.10.0.0]
      - zipp [required: >=0.5, installed: 3.4.1]
    - iniconfig [required: Any, installed: 1.1.1]
    - packaging [required: Any, installed: 20.9]
      - pyparsing [required: >=2.0.2, installed: 2.4.7]
    - pluggy [required: >=0.12,<1.0.0a1, installed: 0.13.1]
      - importlib-metadata [required: >=0.12, installed: 4.0.1]
        - typing-extensions [required: >=3.6.4, installed: 3.10.0.0]
        - zipp [required: >=0.5, installed: 3.4.1]
    - py [required: >=1.8.2, installed: 1.10.0]
    - toml [required: Any, installed: 0.10.2]
  - pytest-django [required: Any, installed: 4.3.0]
    - pytest [required: >=5.4.0, installed: 6.2.4]
      - attrs [required: >=19.2.0, installed: 21.2.0]
      - importlib-metadata [required: >=0.12, installed: 4.0.1]
        - typing-extensions [required: >=3.6.4, installed: 3.10.0.0]
        - zipp [required: >=0.5, installed: 3.4.1]
      - iniconfig [required: Any, installed: 1.1.1]
      - packaging [required: Any, installed: 20.9]
        - pyparsing [required: >=2.0.2, installed: 2.4.7]
      - pluggy [required: >=0.12,<1.0.0a1, installed: 0.13.1]
        - importlib-metadata [required: >=0.12, installed: 4.0.1]
          - typing-extensions [required: >=3.6.4, installed: 3.10.0.0]
          - zipp [required: >=0.5, installed: 3.4.1]
      - py [required: >=1.8.2, installed: 1.10.0]
      - toml [required: Any, installed: 0.10.2]
  - python-dateutil [required: Any, installed: 2.8.1]
    - six [required: >=1.5, installed: 1.16.0]
  - pytz [required: Any, installed: 2021.1]
  - pyyaml [required: Any, installed: 5.4.1]
  - redis [required: Any, installed: 3.5.3]
  - requests [required: Any, installed: 2.25.1]
    - certifi [required: >=2017.4.17, installed: 2020.12.5]
    - chardet [required: >=3.0.2,<5, installed: 4.0.0]
    - idna [required: >=2.5,<3, installed: 2.10]
    - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.4]
  - six [required: Any, installed: 1.16.0]
  - sqlparse [required: Any, installed: 0.4.1]
  - unidecode [required: Any, installed: 1.2.0]
  - wheel [required: Any, installed: 0.36.2]
  - wit [required: ==4.3.0, installed: 4.3.0]
    - prompt-toolkit [required: Any, installed: 3.0.18]
      - wcwidth [required: Any, installed: 0.2.5]
    - requests [required: >=0.8.8, installed: 2.25.1]
      - certifi [required: >=2017.4.17, installed: 2020.12.5]
      - chardet [required: >=3.0.2,<5, installed: 4.0.0]
      - idna [required: >=2.5,<3, installed: 2.10]
      - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.4]
```

I'm using macOS 11.3.1 but I had the same issue on Ubuntu 20.04 LTS. Please let me know if you require any further information.

**Comment by awais-akhtar** [comment]
write import os in    env\Lib\site-packages\botshot\bootstrap\botshot_settings.py
